### ISSUE TITLE
More programming languages

### ISSUE THREAD

**Issue by mariuscoto** [mariuscoto/github-connect#72]
Add more programming languages to lists.

**Comment by mateioprea** [comment]
added more [here](https://github.com/cmarius02/github-connect/commit/178d88739968ee751c17161bf35096c10805b02a)

**Comment by mariuscoto** [comment]
There are also these files that need to me modified: 
- https://github.com/cmarius02/github-connect/tree/master/views/projects.jade#L44
- https://github.com/cmarius02/github-connect/tree/master/views/idea.jade#L134

It also may be a good idea to have them all stored in one place, so we can easily add/remove more. Check this file (https://github.com/cmarius02/github-connect/blob/master/model/points.js) for macros.

While at it, please set a selected value in places where we have one, like (https://github.com/cmarius02/github-connect/blob/master/views/idea.jade#L134). You can get the selected value with #{idea.lang} and set value in selectpicker with 'selected' atribute.

In the end it should look like this:

``` Jade
select.selectpicker.span5(name='lang', type='text')
- each o in POINTS.LANG
  - if (o == idea.lang)
    option(selected)= o
  - else
    option= o
```

**Comment by mateioprea** [comment]
ok. i'll modify that tonight.
